# Generated by Django 4.2.7 on 2023-11-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app2', '0002_alter_officialsuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialsuser',
            name='password',
            field=models.CharField(max_length=5000),
        ),
    ]
