# Generated by Django 4.2.7 on 2023-12-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app2', '0003_alter_officialsuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
