# Generated by Django 4.2.7 on 2023-12-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app2', '0005_sectionteacher_dailyattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionteacher',
            name='section',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
