# Generated by Django 4.2.7 on 2023-12-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app2', '0006_alter_sectionteacher_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='sectionteacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sectionteacher',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='sectionteacher',
            name='section',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='DailyAttendance',
        ),
    ]
