# Generated by Django 4.2.7 on 2023-12-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app2', '0007_teacherregistration_remove_sectionteacher_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherregistration',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacherregistration',
            name='section',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherregistration',
            name='teacher_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
